---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Cross-account IAM Role for SignalFx monitoring."
Parameters:
  SignalFxAccountID:
    Type: String
    Default: "134183635603"
    Description: Enter the SignalFx Account ID from the Amazon CloudWatch integrations page.
  SignalFxExternalId:
    Type: String
    Description: Enter your External ID from the SignalFx Amazon CloudWatch integrations page.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "SignalFx IDs"
        Parameters:
          - SignalFxAccountID
          - SignalFxExternalId
    ParameterLabels:
      SignalFxAccountID:
        default: SignalFx Account ID
      SignalFxExternalId:
        default: SignalFx External ID

Resources:
  SignalFxPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: Gives SignalFx permission to read information about our AWS usage.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ec2:DescribeInstances"
              - "ec2:DescribeVolumes"
              - "ec2:DescribeTags"
              - "cloudwatch:ListMetrics"
              - "cloudwatch:GetMetricStatistics"
              - "cloudwatch:DescribeAlarms"
              - "sqs:ListQueues"
              - "rds:DescribeDBInstances"
              - "elasticloadbalancing:DescribeLoadBalancers"
              - "elasticloadbalancing:DescribeTags"
              - "elasticache:describeCacheClusters"
              - "dynamodb:ListTables"
            Resource: "*"
  SignalFxRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: SignalFxAccessRole
      ManagedPolicyArns:
        - Ref: SignalFxPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${SignalFxAccountID}:root"
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Sub "${SignalFxExternalId}"

Outputs:
  SignalFxRoleArn:
    Description: "SignalFx Role ARN"
    Value: !GetAtt SignalFxRole.Arn
